<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>UzAI.Infrastructure</RootNamespace>
    <AssemblyName>UzAI.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UzAI.Domain\UzAI.Domain.csproj" />
  </ItemGroup>

</Project>
